### ISSUE TITLE
Can't merge into EnvironmentMap

### ISSUE THREAD

**Issue by csakoda** [amperity/envoy#2]
I encountered this when setting up some tests that override environment variable values.

```
amperity.stitch.e2e-test> (def e (envoy/env-map))
#'amperity.stitch.e2e-test/e
amperity.stitch.e2e-test> e
EnvironmentMap {}
amperity.stitch.e2e-test> (merge e {:asdf 1})
EnvironmentMap ({} [:asdf 1])
```

Perhaps this is expected behavior, if so, what is the justification? I'm finding it would be convenient in test to merge values on top of `envoy/env`.

**Comment by csakoda** [comment]
Also does not work:

```
amperity.stitch.e2e-test> (into e {:asdf 1})
EnvironmentMap ({} :asdf 1)
```

**Comment by greglook** [comment]
Hmm, this definitely seems like a bug. I'm guessing it's [this line](https://github.com/amperity/envoy/blob/800a1dc7c1b25856d4abfbb1a50ce8110ae50eed/src/envoy/core.clj#L216) which looks to be in the reverse order.
