### ISSUE TITLE
EnvironmentMap throws exception with select-keys or find

### ISSUE THREAD

**Issue by jstokes** [amperity/envoy#3]
Using `select-keys` on an environment map uses `find` internally, which will throw an exception when passed a `envoy.core.EnvironmentMap`.

```clojure
(require '[envoy.core :as env :refer [defenv env]])

(defenv :test-bool
  "A boolean field"
  :type :boolean)

(get env :test-bool)
;; => nil
(env :test-bool)
;; => nil
(find env :test-bool)
;; =>
;; 1. Unhandled clojure.lang.ExceptionInfo
;; Cannot parse non-string value to boolean
(select-keys env [:test-bool])
;; =>
;; 1. Unhandled clojure.lang.ExceptionInfo
;; Cannot parse non-string value to boolean
```

**Comment by jstokes** [comment]
It looks like this comes from https://github.com/amperity/envoy/blob/master/src/envoy/core.clj#L228 passing `this` as the default value to `valAt`, which calls `valAt` for `ILookup`, which tries to `(on-access! k this)`

**Comment by greglook** [comment]
Hmm - `entryAt` should probably just be using `nil` as the default there, since it isn't valid for environment variables to be present-but-nil.
