### ISSUE TITLE
cljdoc

### ISSUE THREAD

**Issue by martinklepsch** [amperity/envoy#7]
Hey there 🙂 I just came by by random chance and noticed that you have a badge for API docs in your readme but that those are outdated. And so I wanted to make you aware of [envoy's docs on cljdoc](https://cljdoc.xyz/d/amperity/envoy/0.3.2/doc/readme) that you could use for API documentation [and more](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc). 

There's also a badge and a URL that always points to the most recent release version:

```markdown
[![envoy cljdoc badge](https://cljdoc.xyz/badge/amperity/envoy)](https://cljdoc.xyz/d/amperity/envoy/CURRENT)
```

[![envoy cljdoc badge](https://cljdoc.xyz/badge/amperity/envoy)](https://cljdoc.xyz/d/amperity/envoy/CURRENT)

It's all open source in case you're curious: https://github.com/cljdoc/cljdoc

**Comment by greglook** [comment]
Very cool! I'll update the links.

**Comment by martinklepsch** [comment]
Looking great! 👍
